import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@/components/Button";
import { AiOutlinePlus } from "react-icons/ai";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pre-Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <br />
        <Header>
          <h1>Logo</h1>
          <Button>Create playlist</Button>
        </Header>
        <br />
        <Button>Create playlist</Button>
        <br />
        <Button variant="button-light" icon={<AiOutlinePlus size={20} />}>
          Create playlist
        </Button>
      </main>
    </>
  );
}
